name: Blog
markdown: redcarpet
pygments: true

permalink: /:title/
title: Blog
tagline: 
description:
url: http://jtescher.github.io/
timezone: 'America/Los_Angeles'

author:
  name: 'Julian Tescher'
  url: https://twitter.com/jatescher
  
paginate: 5

version: 1.0.0
github:
  repo: https://github.com/jtescher/jtescher.github.io
  
ga_domain: jtescher.github.io
ga_tracking_id: UA-47260751-2
  