name: Blog
markdown: redcarpet
pygments: true

permalink: /:title/
title: Julian Tescher Does The Internet
tagline: so wow
description: Julian Tescher Does The Internet. So Wow.
url: https://jtescher.github.io
timezone: 'America/Los_Angeles'

twitter: https://twitter.com/jatescher
author:
  name: 'Julian Tescher'
  email: jatescher@gmail.com
  url: https://twitter.com/jatescher
  
paginate: 5

version: 1.0.0
github:
  profile: https://github.com/jtescher
  download: https://github.com/jtescher/jtescher.github.io/archive/master.zip
  repo: https://github.com/jtescher/jtescher.github.io
  
ga_domain: jtescher.github.io
ga_tracking_id: UA-47260751-2
  